version: "3.8"

services:
  api:
    build:
        context: ./
        dockerfile: ./builds/nodejs_api.Dockerfile
    restart: always
    ports:
      - "${API}:4000"
    volumes: 
      - ./src/api:/usr/app
      - node_modules_api:/usr/data
    networks: 
      - rede
    depends_on:
      - mysql

  frontend:
    build:
        context: ./
        dockerfile: ./builds/nodejs_frontend.Dockerfile
    restart: always
    ports:
      - "${FRONTEND}:3000"
    volumes: 
      - ./src/frontend:/usr/app
      - node_modules_frontend:/usr/data
    networks: 
      - rede

  mysql:
      image: mysql:5.7.35
      volumes: 
        - db_data:/var/lib/mysql
        - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      restart: always
      networks: 
        - rede
      environment:
        MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports: 
      - "${PHPMYADMIN}:80"
    networks: 
      - rede
    depends_on: 
      - mysql
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "root"

volumes: 
  db_data:
  node_modules_api:
  node_modules_frontend:

networks: 
  rede: