// Pacote Nivel
export const ATUALIZAR_NIVEL_DATA = "ATUALIZAR_NIVEL_DATA"
export const GET_NIVEL_ID = "GET_NIVEL_ID"


// Pacote deenvolvedor
export const ATUALIZAR_DESENVOLVEDOR_DATA = "ATUALIZAR_DESENVOLVEDOR_DATA"
export const GET_DESENVOLVEDOR_ID = "GET_NIVEL_DESENVOLVEDOR"