-- MySQL Script generated by MySQL Workbench
-- Thu Dec 23 01:02:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema desafio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `desafio` ;

-- -----------------------------------------------------
-- Schema desafio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafio` DEFAULT CHARACTER SET utf8 ;
USE `desafio` ;

-- -----------------------------------------------------
-- Table `desafio`.`nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio`.`nivel` ;

CREATE TABLE IF NOT EXISTS `desafio`.`nivel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio`.`desenvolvedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio`.`desenvolvedor` ;

CREATE TABLE IF NOT EXISTS `desafio`.`desenvolvedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel_id` INT NOT NULL,
  `nome` VARCHAR(50) CHARACTER SET 'armscii8' NOT NULL,
  `sexo` CHAR NULL,
  `datanascimento` DATE NOT NULL,
  `idade` INT NOT NULL,
  `hobby` VARCHAR(300) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_desenvolvedor_nivel_idx` (`nivel_id` ASC) ,
  CONSTRAINT `fk_desenvolvedor_nivel`
    FOREIGN KEY (`nivel_id`)
    REFERENCES `desafio`.`nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE `desafio`;

INSERT INTO `nivel` (`id`, `nivel`) VALUES
(1, 'Junior'),
(2, 'Pleno'),
(3, 'Senior');

INSERT INTO `desenvolvedor` (`id`, `nivel_id`, `nome`, `sexo`, `datanascimento`, `idade`, `hobby`) VALUES
(1, 2, 'Gustavo Michels de Camargo', 'M', '1998-05-18', 23, 'Ler e ver series.');